### PR TITLE
ЛР_1_ЛР_2_ЛР_3_ЛР_4_Алексеев_Павел_К33421

### PR DESCRIPTION
**Pull request by pashaalexeev17**
DOC: https://pashaalexeev17.github.io/ITMO_ICT_WebDevelopment_2022-2023/

### CODE REVIEW

**Comment by pashaalexeev17** [comment]
DOC LR2: https://pashaalexeev17.github.io/ITMO_ICT_WebDevelopment_2022-2023/lr2/

**Comment by pashaalexeev17** [comment]
DOC LR3: https://pashaalexeev17.github.io/ITMO_ICT_WebDevelopment_2022-2023/lr3/

**Comment by pashaalexeev17** [comment]
DOC LR4: https://pashaalexeev17.github.io/ITMO_ICT_WebDevelopment_2022-2023/lr4/

**Review by TonikX — APPROVED** [review]
Принято!

**Pull request merged**
